### ISSUE TITLE
Forgotten dll in releases

### ISSUE THREAD

**Issue by SKProCH** [Avalon-Group/Voicemeeter-Patch#1]
If you download exe file from [releases page](https://github.com/Avalon-Group/Voicemeeter-Patch/releases/tag/v3.0.2.1) and try to execute it you get an error:
```
The application to execute does not exist: 'C:\Users\SKProCH\Downloads\VoiceMeeterCrack.dll'.
```
In dotnet world you need to provide not only exe file (which acts like a launcher) but a dll file too. 
You you want use it as a single exe file you need to run `dotnet publish` with such arguments: `-p:PublishSingleFile=true --self-contained false -r win-x64`
```shell
dotnet publish -c Release -p:PublishSingleFile=true --self-contained false -r win-x64
```

**Comment by dword64** [comment]
@SKProCH Fixed!
